import Head from "next/head";
//import { Inter } from 'next/font/google'

import Home from "./home";

//const inter = Inter({ subsets: ['latin'] })

const Index = () => {
  return (
    <>
      <Head>
        <title>Charsi Trading Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

Index.getLayout = Home.getLayout;

export default Index;
